version: "3"
services:
  chartmuseum:
    image: "chartmuseum/chartmuseum:latest"
    ports:
      - "8080:8080"
    environment:
      - "DEBUG=1"
      # - "DEPTH=2"
      - "ALLOW_OVERWRITE=1"
      - "STORAGE=local"
      - "STORAGE_LOCAL_ROOTDIR=/charts"
      # - "BEARER_AUTH=1"
      # - "AUTH_REALM=http://localhost:5001/oauth/token"
      # - "AUTH_SERVICE=localhost:5001"
      # - "AUTH_CERT_PATH=/config/server.pem"
    volumes:
      # - "./config:/config:ro"
      - "./data/charts:/charts:rw"