export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCH_CHARTS = 'FETCH_CHARTS';
export const FETCH_CHARTS_SUCCESS = 'FETCH_CHARTS_SUCCESS';
export const FETCH_CHARTS_ERROR = 'FETCH_CHARTS_ERROR';
export const UPLOAD_CHARTS_SUCCESS = 'UPLOAD_CHARTS_SUCCESS';
export const UPLOAD_CHARTS_ERROR = 'UPLOAD_CHARTS_ERROR';
