#!/bin/bash
PWD=`pwd`

declare charts=(
stable/quassel
stable/rabbitmq
stable/rabbitmq-ha
stable/redis
stable/redis-ha
stable/redmine
stable/reloader
stable/rethinkdb
stable/risk-advisor
stable/rocketchat
stable/rookout
stable/sapho
stable/satisfy
stable/schema-registry-ui
stable/sealed-secrets
stable/searchlight
stable/selenium
stable/sematext-agent
stable/sematext-docker-agent
stable/sensu
stable/sentry
stable/seq
stable/signalfx-agent
stable/signalsciences
stable/socat-tunneller
stable/sonarqube
stable/sonatype-nexus
stable/spark
stable/spark-history-server
stable/spartakus
stable/spinnaker
stable/spotify-docker-gc
stable/spring-cloud-data-flow
stable/stackdriver-exporter
stable/stash
stable/stellar-core
stable/stolon
stable/sugarcrm
stable/suitecrm
stable/sumokube
stable/sumologic-fluentd
stable/superset
stable/swift
stable/sysdig
stable/telegraf
stable/tensorflow-notebook
stable/tensorflow-serving
stable/terracotta
stable/testlink
stable/tomcat
stable/traefik
stable/uchiwa
stable/unbound
stable/unifi
stable/vault-operator
stable/velero
stable/verdaccio
stable/voyager
stable/wavefront
stable/weave-cloud
stable/weave-scope
stable/wordpress
stable/xray
stable/zeppelin
stable/zetcd
wunder/shuttle-iam
)

echo "$PWD"

cd $PWD/data/charts
for chart in ${charts[@]}; do
  helm fetch $chart
done